

const placeOrderUsers = async (orderDetails:any) => {
  try {





    
  } catch (error) {
    console.error('Error placing order:', error);
    throw error;
  }
}